version: '3'

services:
  gtdb:
    image: marftoru/mysql:8.1.0-max
    container_name : gtdb
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
#    ports:
#      - '3306:3306'
    restart: unless-stopped
    volumes:
      - './gtareas-db:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=gtareas
      - MYSQL_DATABASE=gtareas
      - TZ=America/Montevideo
      - LANG=C.UTF-8
#    healthcheck:
#      test: "exit 0"
    networks:
      gtnet:
        ipv4_address: 192.168.66.2

  gtredis:
    image: redis:bookworm
    container_name : gtredis
    restart: unless-stopped
    depends_on:
      - gtdb
#        condition: service_healthy
    networks:
      gtnet:
        ipv4_address: 192.168.66.3

  gtmail:
    image: rnwood/smtp4dev:v3
    container_name : gtmail
    ports:
      - '5000:80'
    restart: unless-stopped
    environment:
      - ServerOptions__HostName=gtmail
    depends_on:
      - gtdb
#        condition: service_healthy
    networks:
      gtnet:
        ipv4_address: 192.168.66.4

  gtoauth:
    image: marftoru/laravel:php82-redis
    container_name : gtoauth
#    ports:
#      - '8003:8000'      
    restart: unless-stopped
    environment:
      - APP_NAME=gtareas
      - CACHE_DRIVER=redis
      - DB_CONNECTION=mysql
      - DB_HOST=gtdb
      - DB_PORT=3306
      - DB_DATABASE=gtareas
      - DB_USERNAME=root
      - DB_PASSWORD=gtareas
      - QUEUE_CONNECTION=database
      - MAIL_MAILER=smtp
      - MAIL_HOST=gtmail
      - MAIL_PORT=25
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ENCRYPTION=ssl
      - MAIL_FROM_ADDRESS="no-reply@gtareas.com"
      - REDIS_HOST=gtredis
      # Se debe cambiar los párametros de esta variable por la IP y Puerto del servidor al cual ingresarán los Clientes a la Web de Gestor de Tareas.
      - SERVER_RESTABLECER_PASSWORD=http://192.168.0.2:8000
      # - SERVER-RESTABLECER_PASSWORD=http://localhost:8000
      - SESSION_LIFETIME=60
    volumes:
      - './gtareas-oauth:/app'
    depends_on:
      - gtdb
#        condition: service_healthy
      - gtredis
#        condition: service_started
      - gtmail
#        condition: service_started
    networks:
      gtnet:
        ipv4_address: 192.168.66.5

  gtapi:
    image: marftoru/laravel:php82-redis
    container_name : gtapi
#    ports:
#      - '8002:8000' 
    restart: unless-stopped
    environment:
      - APP_NAME=gtareas
      - CACHE_DRIVER=redis
      - DB_HOST=gtdb
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=gtareas
      - DB_DATABASE=gtareas
      - REDIS_HOST=gtredis
      - GTOAUTH_AUTENTICADO=gtoauth:8000/api/auth/autenticado
      - MAIL_MAILER=smtp
      - MAIL_HOST=gtmail
      - MAIL_PORT=25
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ENCRYPTION=ssl
      - MAIL_FROM_ADDRESS="no-reply@gtareas.com"
      - SESSION_LIFETIME=60
      - SESSION_LASTACCESS=20
      - CATEGORIAS=Análisis,Diseño,Implementación,Verificación,Mantenimiento
      - ESTADOS=Activa,En espera,Atrasada,Cancelada,Finalizada
    volumes:
      - './gtareas-api:/app'
    depends_on:
      - gtdb
#        condition: service_healthy
      - gtredis
#        condition: service_started
      - gtoauth
#        condition: service_started
      - gtmail
#        condition: service_started
    networks:
      gtnet:
        ipv4_address: 192.168.66.6

#  gtlogin:
#    image: marftoru/laravel:php82-redis
#    container_name : gtlogin
#    ports:
#      - '8001:8000'
#    restart: unless-stopped
#    environment:
#      - APP_NAME=gtareas
#      - GTOAUTH_LOGIN=gtoauth:8000/api/auth/login
#      - GTOAUTH_LOGOUT=gtoauth:8000/api/auth/logout
#      - GTOAUTH_AUTENTICADO=gtoauth:8000/api/auth/autenticado
#      - GTOAUTH_USUARIOS=gtoauth:8000/api/usuarios
#      - GTOAUTH_PASSWORD=gtoauth:8000/api/password
#      - GTAPI_TAREAS=gtapi:8000/api/tareas
#      - GTFRONTEND_WEB=http://192.168.0.2:8000
#      - SESSION_DRIVER=cookie
#      - SESSION_LIFETIME=60
#      - SESSION_LASTACCESS=20
#      - CATEGORIAS=Análisis,Diseño,Implementación,Verificación,Mantenimiento
#      - ESTADOS=Activa,En espera,Atrasada,Cancelada,Finalizada
#    volumes:
#      - './gtareas-login:/app'
#    depends_on:
#      - gtoauth
#        condition: service_started
#    networks:
#      gtnet:
#        ipv4_address: 192.168.66.7

  gtfrontend:
    image: marftoru/laravel:php82-redis
    container_name : gtfrontend
    ports:
      - '8000:8000'
    restart: unless-stopped
    environment:
      - APP_NAME=gtareas
      - GTOAUTH_LOGIN=gtoauth:8000/api/auth/login
      - GTOAUTH_LOGOUT=gtoauth:8000/api/auth/logout
      - GTOAUTH_AUTENTICADO=gtoauth:8000/api/auth/autenticado
      - GTOAUTH_USUARIOS=gtoauth:8000/api/usuarios
      - GTOAUTH_PASSWORD=gtoauth:8000/api/password
      - GTAPI_TAREAS=gtapi:8000/api/tareas
      - GTAPI_ASIGNA=gtapi:8000/api/asigna
      - GTAPI_HISTORIAL_TAREAS=gtapi:8000/api/historial/tareas
      - GTAPI_HISTORIAL_COMENTARIOS=gtapi:8000/api/historial/comentarios
      - GTAPI_CORREOS=gtapi:8000/api/correos
      - GTAPI_COMENTARIOS=gtapi:8000/api/comenta
#      - GTLOGIN_WEB=http://localhost:8001
      - SESSION_DRIVER=cookie
      - SESSION_LIFETIME=60
      - SESSION_LASTACCESS=20
      - CATEGORIAS=Análisis,Diseño,Implementación,Verificación,Mantenimiento
      - ESTADOS=Activa,En espera,Atrasada,Cancelada,Finalizada
    volumes:
      - './gtareas-frontend:/app'
    depends_on:
      - gtapi
#        condition: service_started
    networks:
      gtnet:
        ipv4_address: 192.168.66.8

networks:
  gtnet:
    external: true
