version: '3'

services:
  gtdb:
    image: marftoru/mysql:8.1.0
    container_name : gtdb
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    ports:
      - '3306:3306'
    restart: unless-stopped
    volumes:
      - './gtareas-db:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=gtareas
      - MYSQL_DATABASE=gtareas
      - TZ=America/Montevideo
      - LANG=C.UTF-8
#    healthcheck:
#      test: "exit 0"
    networks:
      gtnet:
        ipv4_address: 192.168.66.2

  memcached:
    image: memcached
    container_name : memcached
    restart: unless-stopped
#    healthcheck:
#      test: "exit 0"
    depends_on:
      - gtdb
#      condition: service_healthy
    networks:
      gtnet:
        ipv4_address: 192.168.66.3

  gtmail:
    image: rnwood/smtp4dev:v3
    container_name : gtmail
    ports:
      - '5000:80'
    restart: unless-stopped
    environment:
      - ServerOptions__HostName=gtmail
    depends_on:
      - gtdb
    networks:
      gtnet:
        ipv4_address: 192.168.66.4

  gtoauth:
    image: marftoru/laravel:10.25.2
    container_name : gtoauth
    ports:
      - '8003:8000'
    restart: unless-stopped
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=gtdb
      - DB_PORT=3306
      - DB_DATABASE=gtareas
      - DB_USERNAME=root
      - DB_PASSWORD=gtareas
#      - CACHE_DRIVER=memcached
      - QUEUE_CONNECTION=database
      - MEMCACHED_HOST=memcached
      - MAIL_MAILER=smtp
      - MAIL_HOST=gtmail
      - MAIL_PORT=25
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ENCRYPTION=ssl
      - MAIL_FROM_ADDRESS="no-reply@gtareas.com"
      # Se debe cambiar los párametros de esta variable por la IP y Puerto del servidor al cual ingresarán los Clientes a la Web de Gestor de Tareas.
      - SERVER_RESTABLECER_PASSWORD=http://gtareas.com:8000
      - SESSION_EXPIRATION=60
    volumes:
      - './gtareas-oauth:/app'
    depends_on:
      - gtdb
#        condition: service_healthy
      - memcached
#        condition: service_healthy
      - gtmail
    networks:
      gtnet:
        ipv4_address: 192.168.66.5

  gtapi:
    image: marftoru/laravel:10.25.2
    container_name : gtapi
    ports:
      - '8002:8000'
    restart: unless-stopped
    environment:
      - DB_HOST=gtdb
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=gtareas
      - DB_DATABASE=gtareas
      - MEMCACHED_HOST=memcached
      - GTOAUTH_AUTENTICADO=gtoauth:8000/api/auth/autenticado
    volumes:
      - './gtareas-api:/app'
    depends_on:
      - gtdb
#        condition: service_healthy
      - memcached
#        condition: service_healthy
      - gtoauth
#        condition: service_started
    networks:
      gtnet:
        ipv4_address: 192.168.66.6

  gtlogin:
    image: marftoru/laravel:10.25.2
    container_name : gtlogin
    ports:
      - '8000:8000'
    restart: unless-stopped
    environment:
      - GTOAUTH_LOGIN=gtoauth:8000/api/auth/login
      - GTOAUTH_LOGOUT=gtoauth:8000/api/auth/logout
      - GTOAUTH_USUARIOS=gtoauth:8000/api/usuarios
      - GTOAUTH_PASSWORD=gtoauth:8000/api/password
      - GTAPI_TAREAS=gtapi:8000/api/tareas
      - SESSION_EXPIRATION=60
#     - GTFRONTEND_WEB=http://gtareas.com:8000
    volumes:
      - './gtareas-login:/app'
    depends_on:
      - gtoauth
#        condition: service_started
    networks:
      gtnet:
        ipv4_address: 192.168.66.7

#  gtfrontend:
#    image: marftoru/laravel:10.25.2
#    container_name : gtfrontend
#    ports:
#      - '8000:8000'
#    restart: unless-stopped
#    environment:
#      GTLOGIN: gtlogin:8000
#      GTLOGIN_WEB: http://gtareas.com:8001
#    volumes:
#      - './gtareas-frontend:/app'
#    depends_on:
#      - gtapi
#        condition: service_started
#    networks:
#      gtnet:
#        ipv4_address: 192.168.66.8

networks:
  gtnet:
    external: true
